<Project Sdk="Microsoft.NET.Sdk.WindowsDesktop">
    <PropertyGroup>
        <AssemblyName>WinResizer.Core</AssemblyName>
        <RootNamespace>WinResizer.Core</RootNamespace>
        <TargetFrameworks>net6.0-windows;netcoreapp3.1;net48;net47</TargetFrameworks>
        <UseWPF>true</UseWPF>
        <UseWindowsForms>true</UseWindowsForms>
        <Nullable>enable</Nullable>
        <LangVersion>Latest</LangVersion>
    </PropertyGroup>
    <ItemGroup>
      <ProjectReference Include="..\WinResizer.Common\WinResizer.Common.csproj" />
      <ProjectReference Include="..\WinResizer.Configuration\WinResizer.Configuration.csproj" />
      <InternalsVisibleTo Include="CaptureGeometryHarness" />
    </ItemGroup>
</Project>
