<Project Sdk="Microsoft.NET.Sdk.WindowsDesktop">

  <PropertyGroup>
    <AssemblyName>WinResizer.Runtime</AssemblyName>
    <RootNamespace>WinResizer.Runtime</RootNamespace>
    <TargetFrameworks>net48;net47</TargetFrameworks>
    <UseWindowsForms>true</UseWindowsForms>
    <Nullable>enable</Nullable>
    <LangVersion>Latest</LangVersion>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\WinResizer.Base\WinResizer.Base.csproj" />
    <ProjectReference Include="..\WinResizer.Common\WinResizer.Common.csproj" />
    <ProjectReference Include="..\WinResizer.Configuration\WinResizer.Configuration.csproj" />
    <ProjectReference Include="..\WinResizer.Core\WinResizer.Core.csproj" />
  </ItemGroup>

</Project>
